export const NOTIFICATION_TYPE = {
    // Event lifecycle
    EVENT: "EVENT",
    EVENT_REMINDER: "EVENT_REMINDER",
    EVENT_CANCELLED: "EVENT_CANCELLED",
    EVENT_UPDATED: "EVENT_UPDATED",
    EVENT_DELETED: "EVENT_DELETED",
    EVENT_JOINED: "EVENT_JOINED",
    EVENT_LEFT: "EVENT_LEFT",
    EVENT_COMPLETED: "EVENT_COMPLETED",
    EVENT_STARTED: "EVENT_STARTED",
    EVENT_ENDED: "EVENT_ENDED",

    // Join requests
    JOIN_REQUEST: "JOIN_REQUEST",
    JOIN_REQUEST_ACCEPTED: "JOIN_REQUEST_ACCEPTED",
    JOIN_REQUEST_REJECTED: "JOIN_REQUEST_REJECTED",

    // Reviews
    REVIEW: "REVIEW",
    REVIEW_UPDATED: "REVIEW_UPDATED",
    REVIEW_DELETED: "REVIEW_DELETED",

    // System
    SYSTEM: "SYSTEM",
}

export const PENDING_JOIN_REQUEST_STATUS = {
    PENDING: "pending",
    ACCEPTED: "accepted",
    REJECTED: "rejected"
}