import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

// Helper to load .env without external dependencies
function loadEnvFile(envPath) {
  if (!fs.existsSync(envPath)) return;
  const content = fs.readFileSync(envPath, 'utf-8');
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eqIdx = line.indexOf('=');
    if (eqIdx === -1) continue;
    const key = line.slice(0, eqIdx).trim();
    let val = line.slice(eqIdx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (!process.env[key]) {
      process.env[key] = val;
    }
  }
}

// Load local .env if present
loadEnvFile(path.join(rootDir, '.env'));

const apiBaseUrl = (process.env.API_BASE_URL || 'https://api.viblooop.com').replace(/\/+$/, '');
const isProduction = process.env.NODE_ENV === 'production' || Boolean(process.env.VERCEL);

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || '',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || 'rk-delta.firebaseapp.com',
  projectId: process.env.FIREBASE_PROJECT_ID || 'rk-delta',
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || 'rk-delta.firebasestorage.app',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '428932858018',
  appId: process.env.FIREBASE_APP_ID || '1:428932858018:web:8ccca497cccfe186d117fb',
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || 'G-ZRC6SHW6KN',
};

const ogImageUrl = process.env.OG_IMAGE_URL || 'https://www.viblooop.com/og.png';
const ogPageUrl = process.env.OG_PAGE_URL || 'https://www.viblooop.com';

// 1. Generate src/environment.ts
const environmentContent = `// Auto-generated by scripts/set-env.mjs — DO NOT COMMIT
const apiServerUrl = '${apiBaseUrl}';

export const Environment = {
  production: ${isProduction},
  version: require('../package.json').version,

  // API URLs
  serverUrl: apiServerUrl,
  apiBaseUrl: \`\${apiServerUrl}/api\`,
  authBaseUrl: \`\${apiServerUrl}/auth\`,
  imageBaseUrl: \`\${apiServerUrl}/\`,

  // Google Maps URLs (external navigation)
  googleMapsSearchUrl: 'https://www.google.com/maps/search/',
  googleMapsUrl: 'https://www.google.com/maps',

  // Firebase Config
  firebase: ${JSON.stringify(firebaseConfig, null, 4)},

  // OG Meta
  ogImageUrl: '${ogImageUrl}',
  ogPageUrl: '${ogPageUrl}',
};
`;

const envFilePath = path.join(rootDir, 'src', 'environment.ts');
fs.writeFileSync(envFilePath, environmentContent.trim() + '\n', 'utf-8');

// 2. Generate src/assets/firebase-messaging-sw.js
const serviceWorkerContent = `// Auto-generated by scripts/set-env.mjs — DO NOT COMMIT
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/9.22.0/firebase-messaging-compat.js');

const firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);

// Retrieve messaging instance
const messaging = firebase.messaging();

// Background message handler
messaging.onBackgroundMessage(function (payload) {
  console.log('[firebase-messaging-sw.js] Background message received:', payload);

  const notificationTitle = payload.notification?.title || 'New Notification';
  const notificationOptions = {
    body: payload.notification?.body,
    icon: '/assets/icons/icon-192x192.png'
  };

  self.registration.showNotification(notificationTitle, notificationOptions);
});
`;

const swFilePath = path.join(rootDir, 'src', 'assets', 'firebase-messaging-sw.js');
fs.writeFileSync(swFilePath, serviceWorkerContent.trim() + '\n', 'utf-8');

console.log('✅ [set-env] Successfully generated src/environment.ts and src/assets/firebase-messaging-sw.js');
